name: Build ESP32-S3 Firmware

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.3 # Kunci ke versi stabil v5.3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone ESP-DSP Submodule
        run: |
          mkdir -p components
          if [ ! -d "components/esp-dsp" ]; then
            git clone --recursive https://github.com/espressif/esp-dsp.git components/esp-dsp
          fi

      - name: Patch Dependencies and CMakeLists
        run: |
          # Hapus lock file versi 6.0
          rm -f dependencies.lock
          # Daftarkan dependensi json, http_server, nvs, wifi ke CMake
          sed -i 's/INCLUDE_DIRS "\."/INCLUDE_DIRS "." REQUIRES json esp_http_server nvs_flash esp_wifi driver esp_pm esp_timer/g' main/CMakeLists.txt

      - name: Build Firmware
        run: |
          . /opt/esp/idf/export.sh
          idf.py build

      - name: Upload Binaries Artifact
        uses: actions/upload-artifact@v4
        with:
          name: esp32s3-firmware-binaries
          path: |
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/esp32s3_audio_dsp.bin
            build/flasher_args.json